### ISSUE TITLE
TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters

### ISSUE THREAD

**Issue by Dev-Yukine** [wopian/kitsu#146]
Using this piece of code
```js
const Kitsu = require('kitsu');
const kitsu = new Kitsu();
const { data } = await kitsu.fetch('anime', { filter: { name: "Attack On Titan"} });
``` 
(used inside an async function) throws following error
```
senpai_1    | [2018-03-08 12:27:30] [0] TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
senpai_1    | [2018-03-08 12:27:30] [0]     at new ClientRequest (_http_client.js:127:13)
senpai_1    | [2018-03-08 12:27:30] [0]     at Object.request (https.js:275:10)
senpai_1    | [2018-03-08 12:27:30] [0]     at RedirectableRequest._performRequest (/usr/src/Senpai/node_modules/follow-redirects/index.js:128:24)
senpai_1    | [2018-03-08 12:27:30] [0]     at new RedirectableRequest (/usr/src/Senpai/node_modules/follow-redirects/index.js:54:8)
senpai_1    | [2018-03-08 12:27:30] [0]     at Object.wrappedProtocol.request (/usr/src/Senpai/node_modules/follow-redirects/index.js:252:14)
senpai_1    | [2018-03-08 12:27:30] [0]     at dispatchHttpRequest (/usr/src/Senpai/node_modules/axios/lib/adapters/http.js:141:25)
senpai_1    | [2018-03-08 12:27:30] [0]     at new Promise (<anonymous>)
senpai_1    | [2018-03-08 12:27:30] [0]     at httpAdapter (/usr/src/Senpai/node_modules/axios/lib/adapters/http.js:18:10)
senpai_1    | [2018-03-08 12:27:30] [0]     at dispatchRequest (/usr/src/Senpai/node_modules/axios/lib/core/dispatchRequest.js:59:10)
senpai_1    | [2018-03-08 12:27:30] [0]     at <anonymous>
``` 
and im pretty sure that this piece of code is correct 🤔 would appreciate some information how i would go about fixing this issue

**Comment by wopian** [comment]
Thanks for making me aware of this! Seems axios itself doesn't handle character escaping - it passes it to `XHR` in browser that does do this automatically, but `http` in node expects you to do it yourself.

Fixed this in https://github.com/wopian/kitsu/commit/e4210fc86e777614457f3ed5428d812bb8df2063 and released in `5.0.6` 👍
