### ISSUE TITLE
Error: Request failed with status code 404

### ISSUE THREAD

**Issue by Toskan4134** [wopian/kitsu#555]
I'm getting this error and I don't know why...
```err
(node:5995) UnhandledPromiseRejectionWarning: Error: Request failed with status code 404
    at createError (/rbd/pnpm-volume/04410727-134b-45fc-bd85-405c5d9cfcc1/node_modules/kitsu/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/rbd/pnpm-volume/04410727-134b-45fc-bd85-405c5d9cfcc1/node_modules/kitsu/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/rbd/pnpm-volume/04410727-134b-45fc-bd85-405c5d9cfcc1/node_modules/kitsu/node_modules/axios/lib/adapters/http.js:260:11)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This is my .js code:
```js
const Kitsu = require('kitsu');
const kitsu = new Kitsu();

kitsu.get("Naruto").then(anime=>{
     console.log(anime)
})
```

**Comment by wopian** [comment]
This request should be either:

```js
// Search all anime that has `Naruto` in its slug, title or synopsis
kitsu.get('anime', { 
  filter: {
    text: 'Naruto'
  }
}).then(anime=>{
  console.log(anime)
})
```

```js
// Get anime with the 'naruto' slug (https://kitsu.io/anime/naruto)
kitsu.get('anime', { 
  filter: {
    slug: 'Naruto'
  }
}).then(anime=>{
  console.log(anime)
})
```

Check `kitsu`'s API documentation at https://github.com/wopian/kitsu/tree/master/packages/kitsu#get and Kitsu.io's API documentation at https://hummingbird-me.github.io/api-docs/#tag/Anime/paths/~1anime~1{id}/get
