### ISSUE TITLE
[object Object] is not an Option Object when defining query parameters in Vue setup context

### ISSUE THREAD

**Issue by voltane** [wopian/kitsu#602]
Hi!
I recently started using this library with following stack:

- Nuxt 2 + Vue 2
- @nuxtjs/composition-api
- Node 16

When query parameter is defined in `setup` method and passed to kitsu `fetch` it throws following error:
` ERROR  [object Object] is not an Option Object 
  at Object.module.exports [as default] (node_modules/kitsu/node_modules/merge-options/index.js:164:10)
  at module.exports.get (node_modules/kitsu/dist/index.js:1:914)`

What i already found is that `merge-options` lib used by kitsu is heavly using lib called `is-plain-obj` and it, following check returns false: `Object.getPrototypeOf(params) === Object.prototype` (https://github.com/sindresorhus/is-plain-obj/blob/6a4cfe72714db0b90fcf6e1f78a9b118b98d44fa/index.js#L6).
Problem does not occur when parameter passed to kitsu is defined for example in onMouted() hook.
It also throws an error when api is used in composables (later used in setup).

Here is little, example repo which reproduce this problem: https://github.com/voltane/kitsu-obj-bug

**Comment by voltane** [comment]
Indeed the spread works nice here (i did it locally) but i didn't know what was the purpose of `merge-options` usage :) Anyways, thanks for fix :tada:
